# Generated by Django 5.2.6 on 2025-10-02 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_recomendacionestudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('total_empleados', models.IntegerField(default=0)),
                ('modulos_completados', models.IntegerField(default=0)),
                ('promedio_general', models.FloatField(default=0.0)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrechaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('porcentaje_bajo', models.FloatField(default=0.0)),
                ('empleados_afectados', models.IntegerField(default=0)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.modulo')),
            ],
        ),
    ]
