# Generated by Django 4.2.25 on 2025-10-16 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_recomendacionestudio'),
        ('tutor_ia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversaciontutor',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='respuestapredefinida',
            name='tags',
            field=models.CharField(default='', help_text='Palabras clave separadas por coma', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversaciontutor',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.modulo'),
        ),
    ]
