# Generated by Django 5.2.6 on 2025-09-30 00:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diagnosticoinicial',
            unique_together={('usuario', 'modulo')},
        ),
    ]
